name: Customer Churn ML CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn xgboost matplotlib seaborn jupyter nbconvert

      - name: Run training notebook
        run: |
          jupyter nbconvert --to notebook --execute cust1_train.ipynb --output result_train.ipynb

      - name: Run prediction notebook
        run: |
          jupyter nbconvert --to notebook --execute cust1_prediction.ipynb --output result_predict.ipynb
